name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  github-token:  # id of input
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
